name: first-workflow
on: 
  push:
    branches: 
      - main
      - 'releases/**'
  pull_request:
    branches: 
      - main
jobs: 
  build:
    runs-on: ubuntu-slim
    steps:
      - name: print hello
        run: echo "Hello world"
      - name: bye
        run: echo "Bye bye!"
      
